// Auth types
export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_FAILED = "AUTH_USER_FAILED";

export const GET_USER_BY_TOKEN = "GET_USER_BY_TOKEN";
export const GET_USER_BY_TOKEN_SUCCESS = "GET_USER_BY_TOKEN_SUCCESS";
export const GET_USER_BY_TOKEN_FAILED = "GET_USER_BY_TOKEN_FAILED";

// Jog types
export const ADD_JOG = "ADD_JOG";
export const ADD_JOG_SUCCESS = "ADD_JOG_SUCCESS";
export const ADD_JOG_FAILED = "ADD_JOG_FAILED";

export const EDIT_JOG = "EDIT_JOG";
export const EDIT_JOG_SUCCESS = "EDIT_JOG_SUCCESS";
export const EDIT_JOG_FAILED = "EDIT_JOG_FAILED";

export const GET_USER_JOGS = "GET_USER_JOGS";
export const GET_USER_JOGS_SUCCESS = "GET_USER_JOGS_SUCCESS";
export const GET_USER_JOGS_FAILED = "GET_USER_JOGS_FAILED";

// Filter types
export const OPEN_FILTER_DIALOG = "OPEN_FILTER_DIALOG";
export const CLOSE_FILTER_DIALOG = "CLOSE_FILTER_DIALOG";

export const SET_FILTER_VALUES = "SET_FILTER_VALUES";
export const REMOVE_FILTER_VALUES = "REMOVE_FILTER_VALUES";
